### ISSUE TITLE
[EPIC] - LQA-Mapping

### ISSUE THREAD

**Issue by EddeCCC** [dqualizer/dqtranslator#4]
## Dependencies

...

## Description

Mapping of the modeling to a rqa-configuration (monitoring, resilience test, load test)

## Issues

- [ ] Mapping of load tests configurations
- [ ] Mapping of monitoring configurations
- [ ] Mapping of resilience configurations

## Additional context
...
